#!/bin/zsh

if [ -z "$1" ]; then
  echo "Usage: javacreate <classname>"
  exit 1
fi

classname="$1"

filename="${classname}.java"

if [ -e "$filename" ]; then
  print -P "%F{red}Error: File %B$filename%b already exists.%f"
  exit 1
fi

cat <<EOF > "$filename"
import java.io.*;
import java.util.*;
import javax.swing.*;

public class ${classname} {
    public static void main(String[] args) throws IOException {
        System.out.println("grug");
    }
}
EOF

# mv "$filename" ~/code/sync
print -P "%F{green}Successfully saved a dozen seconds and created%f $filename"
