#!/bin/zsh

echo ">> Adding dir: /home/carbon/code/sync"
echo ""
git add /home/$(whoami)/code/sync
echo ">> Generating commit message..."
git commit -m "Updated from <$(whoami)> on <$(hostname)> on <$(date)> - Message: $1"
echo ""
echo ">> Committed changes with message:"
echo ">> Updated from <$(whoami)> on <$(hostname)> on <$(date)> - Message: $1"
echo ">> Pushing to sync repo..."
echo ""
git push
echo ">> Success!"
