#!/bin/zsh

print -P "%F{green}>> Adding dir: /home/carbon/code/sync%f"
git add /home/$(whoami)/code/sync
print -P ">> Generating commit message..."
git commit -m "Updated from <$(whoami)> on <$(hostname)> on <$(date)> - Message: $1"
print -P ""
print -P ">> Committed changes with message:"
print -P ">> Updated from <$(whoami)> on <$(hostname)> on <$(date)> - Message: $1"
print -P ">> Pushing to sync repo..."
print -P ""
git push
print -P ">> Success!"
